spring:
  profiles:
    active: dev
  main:
    banner-mode: off
  application:
    name: knowledge-graph-algorithrm-service
  ai:
    mcp:
      server:
        name: knowledge-graph-algorithrm-service
        type: ASYNC
        enabled: true
        version: 1.0.0
        sse-endpoint: /sse
        sse-message-endpoint: /mcp/message
        request-timeout: 30000
       












