server:
  port: 5821
logging:
  level:
    io:
      modelcontextprotocol:
        client: DEBUG
        spec: DEBUG
graph:
  api:
    base-url: http://192.168.3.78:28080/api/v1.2/graph-connections/1/gremlin-query




