spring:
  profiles:
    active: dev
  main:
    banner-mode: off
  application:
    name: graph-server
  ai:
    mcp:
      server:
        name: graph-server
        type: ASYNC
        enabled: true
        sse-endpoint: /sse
        sse-message-endpoint: /mcp/message










